<?php

use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$now = \Carbon\Carbon::now();

	    DB::table('posts')->insert([
	    	[
			    'type' => 'movie',
			    'path' => 'path-to-post',
			    'title' => 'A Movie',
			    'subtitle' => 'A movie subtitle',
			    'content' => 'some content for the post',
			    'link' => 'http://www.imdb.com/title/tt0114709/',
			    'rating' => \Almanac\Posts\PostRating::FINE,
			    'year' => 2012,
			    'spoilers' => false,
			    'date_completed' => $now,
			    'creator' => 'Edgar Wright',
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
				'type' => 'tv',
				'path' => 'path-to-post',
				'title' => 'A TV Show',
				'subtitle' => 'TV subtitle',
				'content' => 'some content for the post',
				'link' => 'https://imdb.com',
				'rating' => \Almanac\Posts\PostRating::NOT_RECOMMENDED,
				'year' => null,
				'date_completed' => $now,
				'season' => '1-5',
			    'spoilers' => false,
			    'creator' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'game',
			    'path' => 'path-to-post',
			    'title' => 'A game',
			    'content' => 'some content',
			    'link' => 'https://efdbsgo.com',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2012,
			    'spoilers' => true,
			    'date_completed' => $now,
			    'creator' => 'Guerilla Games',
			    'subtitle' => null,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'game',
			    'path' => 'path-to-post',
			    'title' => 'An other platform game',
			    'content' => 'some content',
			    'link' => 'https://efdbsgo.com',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2012,
			    'spoilers' => true,
			    'date_completed' => $now,
			    'creator' => 'Guerilla Games',
			    'subtitle' => null,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => 'Amiga',
		    ],
		    [
			    'type' => 'music',
			    'path' => 'path-to-post',
			    'title' => 'Music title',
			    'content' => 'some content',
			    'link' => 'https://spotify.com/playlist/blah',
			    'rating' => \Almanac\Posts\PostRating::FINE,
			    'year' => 2018,
			    'date_completed' => $now,
			    'creator' => 'OST',
			    'subtitle' => null,
			    'spoilers' => false,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'book',
			    'path' => 'path-to-post',
			    'title' => 'A book',
			    'content' => 'some content',
			    'link' => 'http://amazon.com/dfsinagifs',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2017,
			    'spoilers' => true,
			    'date_completed' => $now,
			    'creator' => 'Iain Broome',
			    'subtitle' => null,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'podcast',
			    'path' => 'path-to-post',
			    'title' => 'Bonanza',
			    'subtitle' => 'Amazing',
			    'content' => 'Some content',
			    'link' => 'https://relay.fm/bonanza/1',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2016,
			    'date_completed' => $now,
			    'creator' => 'Matt Alexander and Myke Hurley',
			    'spoilers' => false,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'video',
			    'path' => 'path-to-post',
			    'title' => 'CGP GREY VIDEO',
			    'content' => 'some content',
			    'link' => 'https://www.youtube.com/watch?v=R9OHn5ZF4Uo',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2017,
			    'date_completed' => $now,
			    'creator' => 'CGP GREY',
			    'subtitle' => null,
			    'spoilers' => false,
			    'season' => null,
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
		    [
			    'type' => 'comic',
			    'path' => 'path-to-post',
			    'title' => 'Back to the Future',
			    'content' => 'some content',
			    'link' => 'https://www.youtube.com/watch?v=R9OHn5ZF4Uo',
			    'rating' => \Almanac\Posts\PostRating::RECOMMENDED,
			    'year' => 2017,
			    'date_completed' => $now,
			    'creator' => 'CGP GREY',
			    'subtitle' => null,
			    'spoilers' => false,
			    'season' => 'Back to the Future (IDW)',
			    'created_at' => $now,
			    'updated_at' => $now,
			    'platform' => null,
		    ],
	    ]);
    }
}
